# Generated by Django 4.0 on 2022-07-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='roll',
        ),
    ]
